version: '3'
services:
    main:
        build: .
        container_name: main_contianer
        depends_on:
           - db
        ports:
            - "8001:80"
        volumes:
            - ./:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:latest
        container_name: database
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: POS
            MYSQL_ROOT_PASSWORD: test
        command: --default-authentication-plugin=mysql_native_password
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        depends_on:
          - db
        links:
            - db:db
        ports:
            - 8000:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test